version: '3'
services:
  comum-postgres:
    container_name: comum-postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - comum_data:/var/lib/postgres/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]