version: '3.8'
services:
  comum-postgres:
    container_name: comum-postgres
    image: postgres
    volumes:
      - comum_data:/var/lib/postgres/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MAX_CONNECTIONS: 200
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    ports:
      - "5433:5432"