version: '3.8'
services:
  logstash:
    image: logstash:8.6.2
    container_name: logstash
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline:ro
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5044:5044"
      - "5000:5000/udp"
      - "5000:5000/tcp"
      - "9600:9600"