CREATE SCHEMA comum;
CREATE SCHEMA auditoria;

CREATE TABLE auditoria.operacao_log_auditoria (
    id smallint generated by default as identity primary key,
    descricao varchar(50) not null);

CREATE TABLE auditoria.log_auditoria (
    id bigint generated by default as identity primary key,
    evento varchar(255) not null,
    entidade text not null,
    usuario_logado varchar(200) not null,
    operacao smallint not null,
    data_ocorrencia timestamp without time zone);

ALTER TABLE auditoria.log_auditoria
    ADD CONSTRAINT pk_log_auditoria_operacao
    FOREIGN KEY (operacao) REFERENCES auditoria.operacao_log_auditoria(id);

CREATE TABLE comum.banco(
    id bigint generated by default as identity primary key,
    nome varchar(200) not null,
    codigo varchar(10) not null,
    removido boolean not null default false);

CREATE TABLE comum.centro_de_custo(
    id bigint generated by default as identity primary key,
    descricao varchar(200) not null,
    removido boolean not null default false);

CREATE TABLE comum.departamento(
    id bigint generated by default as identity primary key,
    descricao varchar(200) not null,
    removido boolean not null default false);

CREATE TABLE comum.projeto(
    id bigint generated by default as identity primary key,
    descricao varchar(200) not null,
    removido boolean not null default false);

CREATE TABLE comum.classificacao_orcamentaria(
    id bigint generated by default as identity primary key,
    nome varchar(200) not null,
    descricao varchar(200) not null,
    sintetico boolean not null default false,
    receita boolean not null default false,
    permanente boolean not null default false,
    removido boolean not null default false,
    pai bigint null);

ALTER TABLE comum.classificacao_orcamentaria
    ADD CONSTRAINT pk_pai_classificacao_orcamentaria
    FOREIGN KEY (pai) REFERENCES comum.classificacao_orcamentaria(id);

CREATE TABLE comum.plano_de_contas(
    id bigint generated by default as identity primary key,
    nome varchar(200) not null,
    descricao varchar(200) not null,
    sintetico boolean not null default false,
    receita boolean not null default false,
    transferenciaEntreContas boolean not null default false,
    removido boolean not null default false,
    pai bigint null);

ALTER TABLE comum.plano_de_contas
    ADD CONSTRAINT pk_pai_plano_de_contas
        FOREIGN KEY (pai) REFERENCES comum.plano_de_contas(id);